### ISSUE TITLE
Repeated SSL Connection Failures

### ISSUE THREAD

**Issue by WALLTECH** [ustccw/AzureESP32#1]
Hello, when connecting using the example, the ESP32 constantly reboots with this error:

```
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.

Info: OpenSSL thread start...

Info: create socket ......

I (10482) wifi: pm start, type:0

Info: lwip_net_errno ret: 119

SSL connect... 
Error: Time:Tue May 16 08:08:09 2017 File:C:/msys32/esp/esp-idf/AzureESP32/components/azure_iot/adapter/azure/c-utility/tlsio_ssl_esp32.c Func:openssl_thread_LWIP_CONNECTION Line:348 SSL_connect failed 

SSL_connect failed 
Error: Time:Tue May 16 08:08:09 2017 File:C:/msys32/esp/esp-idf/AzureESP32/components/azure_iot/adapter/azure/c-utility/tlsio_ssl_esp32.c Func:tlsio_openssl_open Line:567 send_handshake_bytes failed.

Guru Meditation Error of type LoadProhibited occurred on core  0. Exception was unhandled.
Register dump:
PC      : 0x4014278d  PS      : 0x00060130  A0      : 0x8012266c  A1      : 0x3ffc7500  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x3ffbd314  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x3ffc744f  A8      : 0x3ffc7620  A9      : 0x3ffc7600  
A10     : 0x00000000  A11     : 0x40118c64  A12     : 0x3ffb9074  A13     : 0x40118d8c  
A14     : 0x3ffb9074  A15     : 0x40118c64  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000018  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x4014278d:0x3ffc7500 0x4012266c:0x3ffc7520 0x4011ac00:0x3ffc7540 0x4014260a:0x3ffc7560 0x40118c28:0x3ffc7580 0x40118c61:0x3ffc75b0 0x40118c74:0x3ffc75d0 0x4011b28d:0x3ffc7600 0x401425e8:0x3ffc7620 0x4011975f:0x3ffc7650 0x40117690:0x3ffc7680 0x40117732:0x3ffc76d0 0x4011831b:0x3ffc7700 0x40115f7c:0x3ffc7730 0x40114b16:0x3ffc7750 0x40113262:0x3ffc7780 0x40112ed7:0x3ffc77d0

Rebooting...
```

**Comment by WALLTECH** [comment]
Another ESP32 Azure example that uses SSL too on the same network consistently works

**Comment by ustccw** [comment]
@WALLTECH 
i am so sorry to have noticed your problem now.
about your issues, i would explain it from two main points.
**1.why SSL connect failed?**
according to your logs,**lwip_net_errno ret: 119** means that SSL is trying to connect to server,errno defined in esp-idf/components/newlib/include/sys/errno.h#150  #define EINPROGRESS 119
according to your logs,**openssl_thread_LWIP_CONNECTION Line:348 SSL_connect failed**,means that SSL connect times beyond its MAX_RETRY,you can follow it at file AzureESP32/components/azure_iot/adapter/azure/c-utility/tlsio_ssl_esp32.c#348
**the most likely reason** for connecting beyond MAX_RETRY is that your **connectionString was invalid** which defined in AzureESP32/main/iothub_client_sample_mqtt.c#21,you have better to get a valid connectionString from microsoft by guide https://www.azure.cn/home/features/iot-hub/

**2. why resulting in a ESP32 crash?**
it caused by the incorrect high layer operation as far as i'm concerned, such as double call tlsio_openssl_close(). and this repository's initial version was based on microsoft works while i am not familiar with their code workflow.
we could exchange more ideas if you want to know more details by seeking for help from microsoft engineers.
please let me know if any question.

**Comment by RonnyA** [comment]
I experience exacatly the same errror and my connection string is *not* wrong.
However when I follow the description here https://github.com/Azure-Samples/iot-hub-c-esp32 (with this bugfix https://github.com/Azure/azure-c-shared-utility/issues/94) the SSL connection works.
I assume there is some differences in your version of the code around SSL

**Comment by ustccw** [comment]
thanks for your ideas. to be honest, ssl connection works well on my side.
if you still have ssl connection failed on this repository, would you mind packing all of your SDKs and send to email: ustccw@163.com to help me find out bugs of this repository. thank you.

**Comment by ms-iotkithol-jp** [comment]
HI, has this problem not been resolved yet?
Today(15 Oct. 2018) I try this. Same situation happens.

-- make monitor --
Initializing SNTP
ESP32 sntp inited!
I (12761) platform: The current date/time in Shanghai is: Mon Oct 15 16:37:26 2018
Info: IoT Hub SDK for C, version 1.1.8
IoTHubClient_LL_SetMessageCallback...successful.
Ready to Send String:{"deviceId":"AirConditionDevice_001","windSpeed":14.00}
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Info: OpenSSL thread start...
Info: create socket ......
Info: lwip_net_errno ret: 119
-- make monitor --

I checked my connection string validity and tried re-generated SAS Token but it didn't work.
Today I cloned this repository by ...
git clone --recursive <<this repository>>.git

Please let me know how to solve it if this problem.

**Comment by 9lash** [comment]
I am also experiencing the same error as reported by ms-iotkithol-jp even if the issue says its been solved. 

Here's my make monitor output:
 
I (2972) platform: The current date/time in Shanghai is: Sat Mar 23 05:20:15 2019
Info: IoT Hub SDK for C, version 1.1.8
IoTHubClient_LL_SetMessageCallback...successful.
Ready to Send String:{"deviceId":"AirConditionDevice_001","windSpeed":12.00}
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Info: OpenSSL thread start...
Info: create socket ......
D (3152) phy_init: wifi mac time delta: 48548
D (3252) phy_init: wifi mac time delta: 96621
D (3352) phy_init: wifi mac time delta: 96593
I (2972) platform: The current date/time in Shanghai is: Sat Mar 23 05:20:15 2019
Info: IoT Hub SDK for C, version 1.1.8
IoTHubClient_LL_SetMessageCallback...successful.
Ready to Send String:{"deviceId":"AirConditionDevice_001","windSpeed":12.00}
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Info: OpenSSL thread start...
Info: create socket ......
D (3152) phy_init: wifi mac time delta: 48548
D (3252) phy_init: wifi mac time delta: 96621
D (3352) phy_init: wifi mac time delta: 96593
I (2972) platform: The current date/time in Shanghai is: Sat Mar 23 05:20:15 2019
Info: IoT Hub SDK for C, version 1.1.8
IoTHubClient_LL_SetMessageCallback...successful.
Ready to Send String:{"deviceId":"AirConditionDevice_001","windSpeed":12.00}
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Info: OpenSSL thread start...
Info: create socket ......
D (3152) phy_init: wifi mac time delta: 48548
D (3252) phy_init: wifi mac time delta: 96621
D (3352) phy_init: wifi mac time delta: 96593
I (2972) platform: The current date/time in Shanghai is: Sat Mar 23 05:20:15 2019
Info: IoT Hub SDK for C, version 1.1.8
IoTHubClient_LL_SetMessageCallback...successful.
Ready to Send String:{"deviceId":"AirConditionDevice_001","windSpeed":12.00}
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Info: OpenSSL thread start...
Info: create socket ......
D (3152) phy_init: wifi mac time delta: 48548
D (3252) phy_init: wifi mac time delta: 96621
D (3352) phy_init: wifi mac time delta: 96593
Info: lwip_net_errno ret: 119
D (30982) phy_init: wifi mac time delta: 96609
D (31082) phy_init: wifi mac time delta: 96601
D (31192) phy_init: wifi mac time delta: 96617
SSL connect... 
SSL_connect succeedD (31292) phy_init: wifi mac time delta: 96616
D (31392) phy_init: wifi mac time delta: 92408
D (31492) phy_init: wifi mac time delta: 96612

I have disabled the WiFi and WiFiClientSecure modules in Arduino configuration under make menuconfig.
