### ISSUE TITLE
Problem compiling the sample

### ISSUE THREAD

**Issue by gloveboxes** [ustccw/AzureESP32#2]
Hi there, I'm pretty sure I have the tool chain correctly installed, I can compile the examples blink and helloworld samples.

When I try compiling the AzureESP32 sample I get the following error

GENCONFIG
CC src/bootloader_flash.o
CC src/secure_boot.o
CC src/secure_boot_signatures.o
CC src/flash_partitions.o
CC src/esp_image_format.o
CC src/flash_encrypt.o
CC src/bootloader_random.o
AR libbootloader_support.a
CC log.o
AR liblog.a
CC spi_flash_rom_patch.o
AR libspi_flash.a
CC esp32/cpu_util.o
CC esp32/rtc_clk.o
CC esp32/brownout.o
AR libsoc.a
CC bootloader_start.o
CC flash_qio_mode.o
AR libmain.a
LD bootloader.elf
esptool.py v2.0.1
Building partitions from /home/dave/esp/esp-idf/components/partition_table/partitions_singleapp.csv...
CC app_trace_util.o
CC app_trace.o
AR libapp_trace.a
CC esp_ota_ops.o
AR libapp_update.a
**make[1]: *** No rule to make target 'azure/c-utility/src/xlogging.o', needed by 'libazure_iot.a'.  Stop.
/home/dave/esp/esp-idf/make/project.mk:390: recipe for target 'azure_iot-build' failed
make: *** [azure_iot-build] Error 2**

any clues as to what I need to do to fix?

btw, I'm compiling the sample in the Bash on Ubuntu on Windows 10 subsystem.

Thanks, Dave

**Comment by ustccw** [comment]
Hello,
please try to initialize the submodule of  https://github.com/Azure/azure-iot-sdk-c.git.
you could have a try as the following:
```
$cd ~/AzureESP32/components/azure_iot/azure
$git submodule init
$git submodule update
$cd ~/AzureESP32
$make flash
```
please make sure that you had export **IDF_PATH** and compiler **PATH**
please let me know if any question.

**Comment by gloveboxes** [comment]
hey there, double checked the environment variables and did as you suggested. Still not working...

dave@dgSurfacePro4:~/esp/AzureESP32/components/azure_iot/azure$ git submodule init
Submodule 'components/azure_iot/azure' (https://github.com/Azure/azure-iot-sdk-c.git) registered for path '../azure'
dave@dgSurfacePro4:~/esp/AzureESP32/components/azure_iot/azure$ git submodule update
Cloning into 'components/azure_iot/azure'...
remote: Counting objects: 49303, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 49303 (delta 1), reused 3 (delta 0), pack-reused 49296
Receiving objects: 100% (49303/49303), 43.71 MiB | 180.00 KiB/s, done.
Resolving deltas: 100% (31200/31200), done.
Checking connectivity... done.
Submodule path '../azure': checked out 'f9e387f69446803bf0e25d68b5b719d346d6e742'
dave@dgSurfacePro4:~/esp/AzureESP32/components/azure_iot/azure$ cd ..
dave@dgSurfacePro4:~/esp/AzureESP32/components/azure_iot$ cd ..
dave@dgSurfacePro4:~/esp/AzureESP32/components$ cd ..
dave@dgSurfacePro4:~/esp/AzureESP32$ make all
make[1]: *** No rule to make target 'azure/c-utility/src/xlogging.o', needed by 'libazure_iot.a'.  Stop.
/home/dave/esp/esp-idf/make/project.mk:390: recipe for target 'azure_iot-build' failed
make: *** [azure_iot-build] Error 2

thanks, Dave

**Comment by ustccw** [comment]
hi, you can follow the next command.
`$ ll ~/AzureESP32/components/azure_iot/azure/c-utility/src/`
1. if you could see file xlogging.c,please try:
```
$make clean
$make
```
if still not work,please packet total of your project and send it to me by email: ustccw@163.com

2.if you could not see file xlogging.c
try to initialize submodule again.
```
$cd ~/AzureESP32/components/azure_iot/azure
$git submodule init
$git submodule update
$cd ~/AzureESP32
$make 
```
please let me know if any question.

**Comment by gloveboxes** [comment]
ah when I checked there was no /src/ directory. I did the clean and rerun the submodule init and update and the /src/ directory is now there and I could complete the compile. What is the correct way to clone this repository. I just did a "git clone https://github.com/ustccw/AzureESP32.git".

Thanks for your help, Dave

**Comment by ustccw** [comment]
u r welcome
